- src/main/java/com/chimaera/wagubook/config/QuerydslConfig.java
- src/main/java/com/chimaera/wagubook/controller/SearchController.java
- src/main/java/com/chimaera/wagubook/repository/MemberRepositoryCustom.java
- src/main/java/com/chimaera/wagubook/repository/MemberRepositoryImpl.java
- src/main/java/com/chimaera/wagubook/repository/PostRepositoryCustom.java
- src/main/java/com/chimaera/wagubook/repository/PostRepositoryImpl.java
- src/main/java/com/chimaera/wagubook/repository/StoreRepository.java
- src/main/java/com/chimaera/wagubook/repository/StoreRepositoryCustom.java
- src/main/java/com/chimaera/wagubook/repository/StoreRepositoryImpl.java
- src/main/java/com/chimaera/wagubook/service/SearchService.java
> 예) #9 
> 검색 기능 구현, querydsl 세팅, repository 수정
> [FEAT] 검색 기능 구현, querydsl 세팅, repository 수정

- src/main/java/com/chimaera/wagubook/entity/Category.java
- src/main/java/com/chimaera/wagubook/entity/Store.java
- src/main/java/com/chimaera/wagubook/repository/store/StoreRepositoryCustom.java
- src/main/java/com/chimaera/wagubook/repository/store/StoreRepositoryImpl.java
- src/main/java/com/chimaera/wagubook/service/StoreService.java
- src/main/resources/application.yml
> 예) #13 
> 화면 좌표를 통해 해당하는 Store를 조회하는 동적 쿼리를 JPQL방식에서 QueryDSL방식으로 변경했습니다.
> 😀
> [REFECTOR]/#13-StoreRepository 동적 쿼리 생성 QueryDSL로 변경

- build.gradle
- src/main/generated/com/chimaera/wagubook/entity/QCategory.java
- src/main/generated/com/chimaera/wagubook/entity/QFollow.java
- src/main/generated/com/chimaera/wagubook/entity/QLocation.java
- src/main/generated/com/chimaera/wagubook/entity/QMember.java
- src/main/generated/com/chimaera/wagubook/entity/QMenu.java
- src/main/generated/com/chimaera/wagubook/entity/QPost.java
- src/main/generated/com/chimaera/wagubook/entity/QShare.java
- src/main/generated/com/chimaera/wagubook/entity/QStore.java
- src/main/resources/application.yml
> #19 
> mysql 로 연결 데이터 베이스 변경
로컬 연결 테스트
서버 디비로 연결 테스트
> [FIX]/#19-MySQL 설정

- src/main/java/com/chimaera/wagubook/entity/MemberImage.java
- src/main/java/com/chimaera/wagubook/entity/MenuImage.java
- src/main/java/com/chimaera/wagubook/service/PostService.java
> #2
> S3 테스트 후, Post Image 생성에서 Image 매핑 안되는 문제 수정
> 😀
> Post Image 생성에서 Image 매핑 안되는 문제 수정

- src/main/java/com/chimaera/wagubook/controller/PostController.java
- src/main/java/com/chimaera/wagubook/entity/Member.java
- src/main/java/com/chimaera/wagubook/entity/MemberImage.java
- src/main/java/com/chimaera/wagubook/entity/Menu.java
- src/main/java/com/chimaera/wagubook/entity/MenuImage.java
- src/main/java/com/chimaera/wagubook/exception/ErrorCode.java
- src/main/java/com/chimaera/wagubook/service/MemberService.java
- src/main/java/com/chimaera/wagubook/service/PostService.java
> 예) #2
> Image 수정 시 발생하는 오류 수정
> 😀
> Image 수정 시 오류 수정

- build.gradle
- src/main/java/com/chimaera/wagubook/controller/SearchController.java
- src/main/java/com/chimaera/wagubook/repository/post/PostRepository.java
- src/main/java/com/chimaera/wagubook/repository/post/PostRepositoryCustom.java
- src/main/java/com/chimaera/wagubook/repository/post/PostRepositoryImpl.java
- src/main/java/com/chimaera/wagubook/service/SearchService.java
- src/main/resources/application.yml
> 예) #9 
> search querydsl 수정😀
> [FIX]/#9-search 수정

- src/main/java/com/chimaera/wagubook/controller/MemberController.java
> 세션 만료 확인 api 구현

- src/main/java/com/chimaera/wagubook/config/SwaggerBeanConfig.java
- src/main/java/com/chimaera/wagubook/config/SwaggerConfig.java
- src/main/java/com/chimaera/wagubook/exception/ErrorCode.java
- src/main/java/com/chimaera/wagubook/repository/menu/MenuRepository.java
- src/main/java/com/chimaera/wagubook/repository/post/PostRepository.java
- src/main/java/com/chimaera/wagubook/service/PostService.java
- src/main/java/com/chimaera/wagubook/service/StoreService.java
> #38
> Swagger Config 추가 (form-data, json 동시 테스트)
하나의 식당 당 하나의 포스트만 작성되게 막기
JPA 오류로 Query did not return unique result 문제 해결 (main menu)
> 😀
> Post 관련 비즈니스 오류 수정

- src/main/java/com/chimaera/wagubook/controller/ShareController.java
- src/main/java/com/chimaera/wagubook/entity/Share.java
- src/main/java/com/chimaera/wagubook/service/ShareService.java
> 예) #33 
> 사용 안하는 메서드 정리 및 결합 테스트
테스트 OK
> 사용 안하는 메서드 정리 및 결합 테스트

- build.gradle
- src/main/java/com/chimaera/wagubook/controller/PostController.java
- src/main/java/com/chimaera/wagubook/dto/PostCreateRequest.java
- src/main/java/com/chimaera/wagubook/dto/PostResponse.java
- src/main/java/com/chimaera/wagubook/dto/PostUpdateRequest.java
- src/main/java/com/chimaera/wagubook/dto/StoreSearchResponse.java
- src/main/java/com/chimaera/wagubook/entity/Post.java
- src/main/java/com/chimaera/wagubook/exception/GlobalExceptionAdvice.java
- src/main/java/com/chimaera/wagubook/service/PostService.java
- src/main/java/com/chimaera/wagubook/service/StoreService.java
> #38
> @transactional이 빠져있어서 생기는 오류로 인해 해당 어노테이션을 추가하였고, Dto에 @Valid를 추가하여 Request 값의 유효성을 검증하여 주었습니다. 또한, isFinished Attribute의 필요성이 없어져 해당 Attribute를 삭제하였습니다.
추가로 프론트측 요청으로 Response에 빠진 부분을 추가하였습니다. (Create, Update Date)
> 😀
> Post @Transactional, @Valid 추가, isFinished 삭제

- build.gradle
- src/main/java/com/chimaera/wagubook/config/RedisConfig.java
- src/main/java/com/chimaera/wagubook/service/RedisService.java
- src/main/resources/application.yml
> #45
> 투표하기 기능에 사용할 Redis 구축 😀
> 😀
> Redis Setting

- src/main/java/com/chimaera/wagubook/controller/SearchController.java
- src/main/java/com/chimaera/wagubook/dto/response/MemberSearchResponse.java
- src/main/java/com/chimaera/wagubook/exception/ErrorCode.java
- src/main/java/com/chimaera/wagubook/service/MemberService.java
- src/main/java/com/chimaera/wagubook/service/SearchService.java
> [FIX]/#65-팔로잉, 팔로워, each response 수정

- src/main/java/com/chimaera/wagubook/controller/MemberController.java
- src/main/java/com/chimaera/wagubook/controller/PostController.java
- src/main/java/com/chimaera/wagubook/entity/Follow.java
- src/main/java/com/chimaera/wagubook/repository/member/FollowRepository.java
- src/main/java/com/chimaera/wagubook/repository/post/PostRepository.java
- src/main/java/com/chimaera/wagubook/service/MemberService.java
- src/main/java/com/chimaera/wagubook/service/PostService.java
> #38
> Post, Follow 관련 조회에 페이징 추가, Post Permission 고려 수정
> 😀
> Post, Follow 페이징 추가, Permission 고려 수정

- src/main/java/com/chimaera/wagubook/controller/SearchController.java
- src/main/java/com/chimaera/wagubook/repository/store/StoreRepository.java
- src/main/java/com/chimaera/wagubook/service/SearchService.java
> 예) #80
> storeId로 Store찾기 로직 구현
> [FEAT]#80-storeId로 Store찾기 로직 구현

- src/main/java/com/chimaera/wagubook/entity/Share.java
- src/main/java/com/chimaera/wagubook/exception/ErrorCode.java
- src/main/java/com/chimaera/wagubook/service/ShareService.java
> 예) #80
> Share 엔티티에서 HashMap 데이터가 너무 커지는 문제 해결
3개의 스토어를 추가할 때 부터 기본 배열인 255를 넘어서는 오브젝트 크기로 인해 오류 발생
@lob어노테이션을 사용해서 문제 해결
> [FIX]/#80-Share 엔티티에서 HashMap 데이터가 너무 커지는 문제 해결

- build.gradle
- src/main/java/com/chimaera/wagubook/service/S3ImageService.java
> #77
> 이미지 리사이징을 통한 용량 문제 개선
> 😀
> 이미지 리사이징 구현

- src/main/java/com/chimaera/wagubook/controller/MemberController.java
- src/main/java/com/chimaera/wagubook/service/MemberService.java
> [FIX] 프로필 이미지, 프로필 이름 반환 기능 수정

- src/main/java/com/chimaera/wagubook/controller/OpenviduController.java
> [FEAT]/#90-streamer memberId 확인 api 개발

- src/main/java/com/chimaera/wagubook/controller/ShareController.java
- src/main/java/com/chimaera/wagubook/service/ShareService.java
> voteList조회 기능 추가

- src/main/java/com/chimaera/wagubook/controller/OpenviduController.java
> 예) #105
> VoiceOpenvidu API 구현
> VoiceOpenvidu API 구현

- src/main/java/com/chimaera/wagubook/config/SecurityConfig.java
> 예) #109 
> -모바일 환경 cors 문제 수정
> [FIX]/#109-모바일 환경 cors 문제 수정

- src/main/java/com/chimaera/wagubook/config/SecurityConfig.java
- src/main/java/com/chimaera/wagubook/controller/ShareController.java
- src/main/java/com/chimaera/wagubook/service/ShareService.java
> 투표 결과 API 반환값 변경

- src/main/java/com/chimaera/wagubook/dto/response/MemberInfoResponse.java
- src/main/java/com/chimaera/wagubook/service/MemberService.java
> 예) #117
> MemberInfoResponse 수정
> [FEAT]/#117-MemberInfoResponse 수정

- src/main/java/com/chimaera/wagubook/controller/ShareController.java
- src/main/java/com/chimaera/wagubook/entity/Share.java
- src/main/java/com/chimaera/wagubook/repository/redis/RedisLockRepository.java
- src/main/java/com/chimaera/wagubook/repository/redis/RedisRepository.java
- src/main/java/com/chimaera/wagubook/service/ShareService.java
> 예) #15
> [RedisService를 Redis Repository로 변경]
[ Redis Lock을 사용한 동시성 문제 해결]
[shareService 상수값 정리]
[redis lock 키 값 변경]
> redis lock을 사용한 동시성 문제 해결

- src/main/java/com/chimaera/wagubook/config/OpenAiConfig.java
- src/main/java/com/chimaera/wagubook/controller/MemberController.java
- src/main/java/com/chimaera/wagubook/controller/PostController.java
- src/main/java/com/chimaera/wagubook/dto/request/PostCreateRequest.java
- src/main/java/com/chimaera/wagubook/entity/Menu.java
- src/main/java/com/chimaera/wagubook/service/MemberService.java
- src/main/java/com/chimaera/wagubook/service/OpenAiService.java
- src/main/java/com/chimaera/wagubook/service/PostService.java
- src/main/java/com/chimaera/wagubook/service/S3ImageService.java
- src/main/resources/application.yml
> #85
> 테스트 결과 S3 url을 보내주는 것보다 base64로 변환하여 보내주는 것이 정확도가 높은 것 같아 OpenAI에 그렇게 넘겨주었습니다! 이미지 리사이징 사이즈는 추후 조정해놓겠습니다:)
>
>호출할 때마다 비용이 나가니 ㅠㅠ 필요할 때에만 호출해주세요 😭
> 😀
> OpenAI를 이용한 리뷰 자동화 기능 추가

- src/main/java/com/chimaera/wagubook/service/ShareService.java
> [FIX]/-redis 저장 시간 수정

- src/main/java/com/chimaera/wagubook/service/OpenAiService.java
- src/main/java/com/chimaera/wagubook/service/PostService.java
- src/main/resources/application.yml
> #85 
> 텍스트만으로 리뷰 생성할 수 있도록 추가, model 오류 수정
> 😀
> 텍스트만으로 리뷰 생성할 수 있도록 추가

- src/main/java/com/chimaera/wagubook/dto/response/StoreSearchResponse.java
> [Feat]/#-store 검색 시 menu 1개 추가로 전달로 수정

- src/main/java/com/chimaera/wagubook/controller/OpenviduController.java
- src/main/java/com/chimaera/wagubook/entity/LiveRoom.java
- src/main/java/com/chimaera/wagubook/entity/LiveRoomParticipant.java
- src/main/java/com/chimaera/wagubook/repository/liveRoom/LiveRoomParticipantRepository.java
- src/main/java/com/chimaera/wagubook/repository/liveRoom/LiveRoomRepository.java
- src/main/java/com/chimaera/wagubook/service/LiveRoomService.java
> [FEAT]/#-LiveRoomParticipant 부분 추가, 및 openvidu 수정

- src/main/java/com/chimaera/wagubook/service/ShareService.java
> [CHORE]/#128-투표 삭제 기능 수정

- src/main/java/com/chimaera/wagubook/controller/PostController.java
- src/main/java/com/chimaera/wagubook/dto/request/PostAIRequest.java
- src/main/java/com/chimaera/wagubook/dto/response/PostAIResponse.java
- src/main/java/com/chimaera/wagubook/service/OpenAiService.java
- src/main/java/com/chimaera/wagubook/service/PostService.java
> #85
> 프론트측 요청으로 리뷰 자동화 API를 분리하였습니다.
> 😀
> 리뷰 자동화 API 분리

- src/main/java/com/chimaera/wagubook/controller/StoreController.java
- src/main/java/com/chimaera/wagubook/dto/response/StoreResponse.java
- src/main/java/com/chimaera/wagubook/service/StoreService.java
> [FEAT]/#134- response 수정 완료

- build.gradle
- src/main/java/com/chimaera/wagubook/config/JacksonConfig.java
- src/main/java/com/chimaera/wagubook/dto/request/PostCreateRequest.java
- src/main/resources/application.yml
> [FEAT]/#-menuContent 길이 및 특수문자를 위한 jacksonConfig 추가

- src/main/java/com/chimaera/wagubook/controller/ChatSignalHandler.java
- src/main/java/com/chimaera/wagubook/dto/request/WebSocketRequest.java
- src/main/java/com/chimaera/wagubook/dto/response/WebSocketResponse.java
- src/main/java/com/chimaera/wagubook/repository/webRTC/SessionRepository.java
> 예) #140
> httpsession 인증 삭제
memberService 의존성 제거
> httpsession 인증 삭제 및 memberService 의존성 제거

- src/test/java/com/chimaera/wagubook/service/ShareServiceTest.java
- src/test/resources/application.yml
> test/aCpplication.yml local 프로필 설정
> test/aCpplication.yml local 프로필 설정

- src/main/java/com/chimaera/wagubook/repository/webRTC/SessionRepository.java
> 예) #150 
> ThreadSafe한 싱글톤 방식 구현
> REFACTOR/#150-싱글톤 스레드안전하게 변경

- src/main/java/com/chimaera/wagubook/repository/webRTC/SessionRepository.java
> REFACTOR/#150-테스트 완료
